name: CI

# run on pushes and PRs to main (and any other branch you like)
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint & Type-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: TypeScript type-check
        run: npx tsc --noEmit

  build:
    name: Build Preview
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build (no deploy)
        run: npm run build

      # Optional: Upload build artifacts so you can inspect them
      - name: Upload Next build
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next
